### ISSUE TITLE
make fails on openSUSE

### ISSUE THREAD

**Issue by Mailaender** [a-detiste/game-data-packager#1]
I tried to package it as suggested in https://build.opensuse.org/package/show/home:Mailaender:branches:games:tools/game-data-packager but it won't build. I narrowed it down to https://github.com/a-detiste/game-data-packager/blob/master/game_data_packager/steam.py#L28 but I am not sure if and what dependency is missing.

```
[   46s] PYTHONPATH=. python3 tools/expand_vars.py runtime/unreal.desktop.in out/unreal.desktop
[   46s] PYTHONPATH=. python3 tools/expand_vars.py runtime/doom2-masterlevels.desktop.in out/doom2-masterlevels.desktop
[   46s] Traceback (most recent call last):
[   46s]   File "tools/expand_vars.py", line 21, in <module>
[   46s]     from game_data_packager.packaging import (get_native_packaging_system)
[   46s]   File "/home/abuild/rpmbuild/BUILD/game-data-packager-44/game_data_packager/__init__.py", line 33, in <module>
[   46s]     from .build import (HashedFile,
[   46s]   File "/home/abuild/rpmbuild/BUILD/game-data-packager-44/game_data_packager/build.py", line 58, in <module>
[   46s]     from .version import (FORMAT, DISTRO)
[   46s] ImportError: cannot import name 'FORMAT'
[   46s] Traceback (most recent call last):
[   46s]   File "tools/expand_vars.py", line 21, in <module>
[   46s]     from game_data_packager.packaging import (get_native_packaging_system)
[   46s]   File "/home/abuild/rpmbuild/BUILD/game-data-packager-44/game_data_packager/__init__.py", line 33, in <module>
[   46s]     from .build import (HashedFile,
[   46s]   File "/home/abuild/rpmbuild/BUILD/game-data-packager-44/game_data_packager/build.py", line 58, in <module>
[   46s]     from .version import (FORMAT, DISTRO)
[   46s] ImportError: cannot import name 'FORMAT'
[   46s] Makefile:96: recipe for target 'out/launch-unreal-gold.yaml' failed
[   46s] make: *** [out/launch-unreal-gold.yaml] Error 1
[   46s] make: *** Waiting for unfinished jobs....
[   46s] Makefile:96: recipe for target 'out/launch-unreal.yaml' failed
[   46s] make: *** [out/launch-unreal.yaml] Error 1
[   46s] Traceback (most recent call last):
[   46s]   File "tools/expand_vars.py", line 21, in <module>
[   46s]     from game_data_packager.packaging import (get_native_packaging_system)
[   46s]   File "/home/abuild/rpmbuild/BUILD/game-data-packager-44/game_data_packager/__init__.py", line 33, in <module>
[   46s]     from .build import (HashedFile,
[   46s]   File "/home/abuild/rpmbuild/BUILD/game-data-packager-44/game_data_packager/build.py", line 58, in <module>
[   46s]     from .version import (FORMAT, DISTRO)
[   46s] ImportError: cannot import name 'FORMAT'
[   46s] Traceback (most recent call last):
[   46s]   File "tools/expand_vars.py", line 21, in <module>
[   46s]     from game_data_packager.packaging import (get_native_packaging_system)
[   46s]   File "/home/abuild/rpmbuild/BUILD/game-data-packager-44/game_data_packager/__init__.py", line 33, in <module>
[   46s]     from .build import (HashedFile,
[   46s]   File "/home/abuild/rpmbuild/BUILD/game-data-packager-44/game_data_packager/build.py", line 58, in <module>
[   46s]     from .version import (FORMAT, DISTRO)
[   46s] ImportError: cannot import name 'FORMAT'
[   46s] Makefile:96: recipe for target 'out/unreal.desktop' failed
[   46s] make: *** [out/unreal.desktop] Error 1
[   46s] Makefile:96: recipe for target 'out/doom2-masterlevels.desktop' failed
[   46s] make: *** [out/doom2-masterlevels.desktop] Error 1
[   46s] rm out/spacequest.svg out/zork-inquisitor.svg out/wolf-common.svg out/tentacle.svg out/zork-nemesis.svg out/kyrandia2.svg out/grimfandango.svg out/inherit.svg out/comi.svg out/chex.svg out/kingsquest.svg out/maniacmansion.svg
[   46s] error: Bad exit status from /var/tmp/rpm-tmp.kxexdO (%build)
```

**Comment by a-detiste** [comment]
Hi,

What are the contents of generated version.py ?

Here's a sample on my system:
```
#!/usr/bin/python3
GAME_PACKAGE_VERSION = "45"
FORMAT = "deb"
DISTRO = "generic"
```

I do can build this RPM on my SuSE VM; but never ever tried to build it on a Suse build daemon.

Does these buildd even have a /etc/SuSE-release file ?

**Comment by a-detiste** [comment]
There are already so many changes since v44.

Like this one: http://anonscm.debian.org/cgit/pkg-games/game-data-packager.git/commit/?id=7a116e478faf0677df058cb3d57039cfc6bcc929

Can you try again with a git snapshot ?

**Comment by a-detiste** [comment]
Or alternatively remove the PYTHONPATH assignement from this line
`PYTHONPATH=. $(PYTHON) tools/expand_vars.py $< $@` in the makefile.

**Comment by Mailaender** [comment]
I found `/etc/SuSE-release` in package `openSUSE-release`. It says:

```
openSUSE 20160317 (x86_64)
VERSION = 20160317
CODENAME = Tumbleweed
# /etc/SuSE-release is deprecated and will be removed in the future, use /etc/os-release instead
```

Adding it to `BuildRequires` fixes it.
